services:
  selenium:
    image: selenium/standalone-firefox:latest  # Você também pode usar standalone-firefox se preferir o Firefox
    ports:
      - "4444:4444"
    networks:
      - app
        
  python-client:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    ports:
      - "9000:9000"
    volumes:
      - ./python_client:/app
    networks:
      - app
      
networks:
  app:
    driver: bridge
